repos:
- repo: https://github.com/floatingpurr/sync_with_poetry
  rev: 0.2.1
  hooks:
  - id: sync_with_poetry

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-docstring-first
  - id: check-json
  - id: pretty-format-json
    args: [--autofix, --indent, '2']
    exclude: cookiecutter.json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
    exclude: ^(.*/)?(tests)/
  - id: end-of-file-fixer
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: requirements-txt-fixer
  - id: forbid-new-submodules
  - id: trailing-whitespace
  - id: fix-byte-order-marker
  - id: fix-encoding-pragma
    args: [--remove]
  - id: check-case-conflict
  - id: mixed-line-ending

- repo: https://github.com/asottile/pyupgrade
  rev: v2.37.3
  hooks:
  - id: pyupgrade
    args: [--py39-plus]

- repo: https://github.com/myint/docformatter
  rev: v1.4
  hooks:
  - id: docformatter
    args: [--recursive, --in-place, --wrap-summaries=120, --wrap-descriptions=112, --blank]

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs

- repo: https://github.com/bemeurer/beautysh
  rev: v6.2.1
  hooks:
  - id: beautysh

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black
    args: [--config=pyproject.toml]
    exclude: ^(.*/)?(tests)/

- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort
    args: [--settings-path=pyproject.toml]

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []     # optional: list of Conventional Commits types to allow
